version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: 'dist'
  files:
    - '**/*'
  name: react-app-build-$(date +%Y-%m-%d-%H-%M-%S).zip
